version: '3.8'

services:
  # Backend API
  makeup-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=uploads
      - ALLOWED_FORMATS=jpg,jpeg,png,webp
      - OPENCV_CASCADE_PATH=haarcascade_frontalface_alt.xml
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:80
    volumes:
      - ./uploads:/app/uploads
      - ./haarcascade_frontalface_alt.xml:/app/haarcascade_frontalface_alt.xml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  makeup-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    depends_on:
      - makeup-api
    restart: unless-stopped

  # Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - makeup-api
      - makeup-frontend
    restart: unless-stopped
